---
SHOW_ELAPSED_TIME: true
DISABLE_ERRORS: true
DISABLE:
  - SPELL
  - COPYPASTE
  - SECRET
  - REPOSITORY
DISABLE_LINTERS:
  - YAML_V8R
  - REPOSITORY_DEVSKIM
  - MARKDOWN_MARKDOWN_LINK_CHECK
EXCLUDED_DIRECTORIES:
  - build
  - .dart_tool
  - TDC-Studio.app
VALIDATE_ALL_CODEBASE: false
