name: tdc_studio
description: TDC Studio — IDE officiel TUTODECODE Script (.tdc)
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown_plus: ^1.0.7
  google_fonts: ^6.1.0
  provider: ^6.1.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  file_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locales/fr.tdc
